language: python

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
script:
  -  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/team973/robotpy-skeleton/master/install.rb)" travis
