language: python

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          language: python
          python: 3.6
        - os: osx
          language: ruby
script:
  -  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/team973/robotpy-skeleton/master/install.rb)" travis
