language: python

matrix:
    include:
        - os: linux
          dist: trusty
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py36
script:
  -  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/team973/robotpy-skeleton/master/install.rb)" travis
